global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'local-prometheus'
    static_configs:
    - targets: ['localhost:9090']
  
  - job_name: 'local-worker1'
    static_configs:
    - targets: ['192.168.4.117:9100']
