apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-image-renderer
        image: grafana/grafana-image-renderer:latest
        ports:
          - containerPort: 8081
            name: http-renderer
            protocol: TCP
        env:
          - name: HTTP_PORT
            value: "8081"
          - name: HTTP_HOST
            value: 0.0.0.0
          - name: ENABLE_METRICS
            value: "true"
          - name: GRAFANA_IMAGE_RENDERER_PORT
            value: "tcp://localhost:8081"
          - name: GRAFANA_IMAGE_RENDERER_PORT_8080_TCP_ADDR
            value: "localhost"
          - name: GRAFANA_IMAGE_RENDERER_PORT_8080_TCP_PROTO
            value: "tcp"
          - name: GRAFANA_IAMGE_RENDERER_SERVICE_PORT_HTTP
            value: "8081"
          - name: GRAFANA_IMAGE_RENDERER_SERVICE_HOST
            value: "localhost"
          - name: GRAFANA_IMAGE_RENDERER_PORT_8081_TCP_PORT
            value: "8081"
          - name: GRAFANA_IMAGE_RENDERER_PORT_8080_TCP
            value: "tcp://localhost:8081"
          - name: GRAFANA_IAMGE_RENDERER_SERVICE_PORT
            value: "8081"
      - name: grafana
        image: grafana/grafana:8.2.3
        imagePullPolicy: IfNotPresent
        env: 
          - name: GF_RENDERING_CALLBACK_URL
            value: "http://localhost:3000"
          - name: GF_RENDERING_SERVER_URL
            value: "http://localhost:8081/render"
          - name: GF_LOG_FILTERS
            value: "rendering:debug"
          - name: GRAFANA_IMAGE-RENDERER_P0RT
            value: "tcp://localhost:8081"
          - name: GRAFANA_IMAGE_RENDERER_PORT_8081_TCP_ADDR
            value: "localhost"
          - name: GRAFANA_IMAGE_RENDERER_PORT_8081_TCP_PROTO
            value: "tcp"
          - name: GRAFANA_IAMGE_RENDERER_SERVICE_PORT_HTTP
            value: "8081"
          - name: GRAFANA_IMAGE_RENDERER_SERVICE_HOST
            value: "localhost"
          - name: GRAFANA_IMAGE_RENDERER_PORT_8081_TCP_PORT
            value: "8081"
          - name: GRAFANA_IMAGE_RENDERER_PORT_8080_TCP
            value: "tcp://localhost:8081"
          - name: GRAFANA_IAMGE_RENDERER_SERVICE_PORT
            value: "8081"
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: grafana-nfs
            mountPath: /var/lib/grafana
          - name: grafana-conf
            mountPath: /usr/share/grafana/conf
      volumes:
        - name: grafana-nfs
          nfs:
            server: 192.168.0.2
            path: "/prometheus-grafana-nfs/grafana"
        - name: grafana-conf
          nfs:
            server: 192.168.0.2
            path: "/prometheus-grafana-nfs/grafana/conf"

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 30002
    - name: grafana-image-renderer
      port: 8081
      protocol: TCP
      targetPort: 8081
  type: NodePort
