apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    name: prometheus-configmap
data:
  prometheus.yml: |-
    global:
      scrape_interval:     30s
      evaluation_interval: 30s
    scrape_configs:
      - job_name: 'local-prometheus'
        static_configs:
        - targets: ['localhost:9090']

      - job_name: 'lp-prometheus-1'
        static_configs:
        - targets: ['192.168.0.21:9100']

      - job_name: 'm-example-1'
        static_configs:
        - targets: ['192.168.0.11:9100']

      - job_name: 'ap-haproxy-1'
        static_configs:
        - targets: ['192.168.0.1:9100']

      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]  # Look for a HTTP 200 response.
        static_configs:
          - targets:
            - https://example.com
            - https://m-example.com
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: prometheus-blackbox-exporter:9115
